#!/bin/bash

# Imported cluster configuration
export CLUSTER_TYPE="imported"
export EKS_CLUSTER_NAME="eks-cluster-hypd-instrt-0910-p3e"
export AWS_REGION="us-west-2"
export SKIP_CLUSTER_CREATION="true"
export SKIP_CLOUDFORMATION="true"
